/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thanhnhan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LoaiSP service. Represents a row in the &quot;MienTayAds_LoaiSP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.thanhnhan.model.impl.LoaiSPModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.thanhnhan.model.impl.LoaiSPImpl}.
 * </p>
 *
 * @author ThanhNhan
 * @see LoaiSP
 * @see com.thanhnhan.model.impl.LoaiSPImpl
 * @see com.thanhnhan.model.impl.LoaiSPModelImpl
 * @generated
 */
public interface LoaiSPModel extends BaseModel<LoaiSP> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loai s p model instance should use the {@link LoaiSP} interface instead.
	 */

	/**
	 * Returns the primary key of this loai s p.
	 *
	 * @return the primary key of this loai s p
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loai s p.
	 *
	 * @param primaryKey the primary key of this loai s p
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loai s p ID of this loai s p.
	 *
	 * @return the loai s p ID of this loai s p
	 */
	public long getLoaiSPId();

	/**
	 * Sets the loai s p ID of this loai s p.
	 *
	 * @param loaiSPId the loai s p ID of this loai s p
	 */
	public void setLoaiSPId(long loaiSPId);

	/**
	 * Returns the loai s p name of this loai s p.
	 *
	 * @return the loai s p name of this loai s p
	 */
	@AutoEscape
	public String getLoaiSPName();

	/**
	 * Sets the loai s p name of this loai s p.
	 *
	 * @param loaiSPName the loai s p name of this loai s p
	 */
	public void setLoaiSPName(String loaiSPName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LoaiSP loaiSP);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LoaiSP> toCacheModel();

	@Override
	public LoaiSP toEscapedModel();

	@Override
	public LoaiSP toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}