/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thanhnhan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SanPham service. Represents a row in the &quot;MienTayAds_SanPham&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.thanhnhan.model.impl.SanPhamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.thanhnhan.model.impl.SanPhamImpl}.
 * </p>
 *
 * @author ThanhNhan
 * @see SanPham
 * @see com.thanhnhan.model.impl.SanPhamImpl
 * @see com.thanhnhan.model.impl.SanPhamModelImpl
 * @generated
 */
public interface SanPhamModel extends BaseModel<SanPham> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a san pham model instance should use the {@link SanPham} interface instead.
	 */

	/**
	 * Returns the primary key of this san pham.
	 *
	 * @return the primary key of this san pham
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this san pham.
	 *
	 * @param primaryKey the primary key of this san pham
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp ID of this san pham.
	 *
	 * @return the sp ID of this san pham
	 */
	public long getSpId();

	/**
	 * Sets the sp ID of this san pham.
	 *
	 * @param spId the sp ID of this san pham
	 */
	public void setSpId(long spId);

	/**
	 * Returns the sp name of this san pham.
	 *
	 * @return the sp name of this san pham
	 */
	@AutoEscape
	public String getSpName();

	/**
	 * Sets the sp name of this san pham.
	 *
	 * @param spName the sp name of this san pham
	 */
	public void setSpName(String spName);

	/**
	 * Returns the desc of this san pham.
	 *
	 * @return the desc of this san pham
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this san pham.
	 *
	 * @param desc the desc of this san pham
	 */
	public void setDesc(String desc);

	/**
	 * Returns the nguoi dang of this san pham.
	 *
	 * @return the nguoi dang of this san pham
	 */
	@AutoEscape
	public String getNguoiDang();

	/**
	 * Sets the nguoi dang of this san pham.
	 *
	 * @param nguoiDang the nguoi dang of this san pham
	 */
	public void setNguoiDang(String nguoiDang);

	/**
	 * Returns the sdt of this san pham.
	 *
	 * @return the sdt of this san pham
	 */
	@AutoEscape
	public String getSdt();

	/**
	 * Sets the sdt of this san pham.
	 *
	 * @param sdt the sdt of this san pham
	 */
	public void setSdt(String sdt);

	/**
	 * Returns the dia chi of this san pham.
	 *
	 * @return the dia chi of this san pham
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this san pham.
	 *
	 * @param diaChi the dia chi of this san pham
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the gia of this san pham.
	 *
	 * @return the gia of this san pham
	 */
	@AutoEscape
	public String getGia();

	/**
	 * Sets the gia of this san pham.
	 *
	 * @param gia the gia of this san pham
	 */
	public void setGia(String gia);

	/**
	 * Returns the ngay dang of this san pham.
	 *
	 * @return the ngay dang of this san pham
	 */
	public Date getNgayDang();

	/**
	 * Sets the ngay dang of this san pham.
	 *
	 * @param ngayDang the ngay dang of this san pham
	 */
	public void setNgayDang(Date ngayDang);

	/**
	 * Returns the image of this san pham.
	 *
	 * @return the image of this san pham
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this san pham.
	 *
	 * @param image the image of this san pham
	 */
	public void setImage(String image);

	/**
	 * Returns the loai s p ID of this san pham.
	 *
	 * @return the loai s p ID of this san pham
	 */
	public long getLoaiSPId();

	/**
	 * Sets the loai s p ID of this san pham.
	 *
	 * @param loaiSPId the loai s p ID of this san pham
	 */
	public void setLoaiSPId(long loaiSPId);

	/**
	 * Returns the pass word of this san pham.
	 *
	 * @return the pass word of this san pham
	 */
	@AutoEscape
	public String getPassWord();

	/**
	 * Sets the pass word of this san pham.
	 *
	 * @param passWord the pass word of this san pham
	 */
	public void setPassWord(String passWord);

	/**
	 * Returns the loai nguoi dung of this san pham.
	 *
	 * @return the loai nguoi dung of this san pham
	 */
	public int getLoaiNguoiDung();

	/**
	 * Sets the loai nguoi dung of this san pham.
	 *
	 * @param loaiNguoiDung the loai nguoi dung of this san pham
	 */
	public void setLoaiNguoiDung(int loaiNguoiDung);

	/**
	 * Returns the loai mua ban of this san pham.
	 *
	 * @return the loai mua ban of this san pham
	 */
	public int getLoaiMuaBan();

	/**
	 * Sets the loai mua ban of this san pham.
	 *
	 * @param loaiMuaBan the loai mua ban of this san pham
	 */
	public void setLoaiMuaBan(int loaiMuaBan);

	/**
	 * Returns the email of this san pham.
	 *
	 * @return the email of this san pham
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this san pham.
	 *
	 * @param email the email of this san pham
	 */
	public void setEmail(String email);

	/**
	 * Returns the k vid of this san pham.
	 *
	 * @return the k vid of this san pham
	 */
	public long getKVid();

	/**
	 * Sets the k vid of this san pham.
	 *
	 * @param kVid the k vid of this san pham
	 */
	public void setKVid(long kVid);

	/**
	 * Returns the status of this san pham.
	 *
	 * @return the status of this san pham
	 */
	public int getStatus();

	/**
	 * Sets the status of this san pham.
	 *
	 * @param Status the status of this san pham
	 */
	public void setStatus(int Status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SanPham sanPham);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SanPham> toCacheModel();

	@Override
	public SanPham toEscapedModel();

	@Override
	public SanPham toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}