/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thanhnhan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TNOptions service. Represents a row in the &quot;MienTayAds_TNOptions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.thanhnhan.model.impl.TNOptionsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.thanhnhan.model.impl.TNOptionsImpl}.
 * </p>
 *
 * @author ThanhNhan
 * @see TNOptions
 * @see com.thanhnhan.model.impl.TNOptionsImpl
 * @see com.thanhnhan.model.impl.TNOptionsModelImpl
 * @generated
 */
public interface TNOptionsModel extends BaseModel<TNOptions> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t n options model instance should use the {@link TNOptions} interface instead.
	 */

	/**
	 * Returns the primary key of this t n options.
	 *
	 * @return the primary key of this t n options
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t n options.
	 *
	 * @param primaryKey the primary key of this t n options
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this t n options.
	 *
	 * @return the ID of this t n options
	 */
	public long getId();

	/**
	 * Sets the ID of this t n options.
	 *
	 * @param id the ID of this t n options
	 */
	public void setId(long id);

	/**
	 * Returns the option_name of this t n options.
	 *
	 * @return the option_name of this t n options
	 */
	@AutoEscape
	public String getOption_name();

	/**
	 * Sets the option_name of this t n options.
	 *
	 * @param option_name the option_name of this t n options
	 */
	public void setOption_name(String option_name);

	/**
	 * Returns the value of this t n options.
	 *
	 * @return the value of this t n options
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this t n options.
	 *
	 * @param value the value of this t n options
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TNOptions tnOptions);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TNOptions> toCacheModel();

	@Override
	public TNOptions toEscapedModel();

	@Override
	public TNOptions toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}